version: '3.7'

services:

  app:
    image: flask-crud:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: personas
      MYSQL_PORT: 3306
    networks:
      - todo-app
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    volumes:
      - ./todo-mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: personas
    networks:
      - todo-app

volumes:
  todo-mysql-data:

networks:
  todo-app: